# .github/workflows/snake.yml
name: Generate Snake Animation

on:
  schedule: # Runs every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: varshavikraman
          outputs: dist/snake.svg

      - name: Upload Snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "update snake"
          add: "dist/snake.svg"
